### ISSUE TITLE
dash-daq-omega-pid example fails with updated versions of the dash repos

### ISSUE THREAD

**Issue by cldougl** [plotly/dash-daq-monorepo#3]
https://github.com/plotly/dash-daq-monorepo/blob/master/dash-apps/dash-daq-omega-pid/ will fail with 
```
Running on http://127.0.0.1:8050/
Debugger PIN: 483-653-516
 * Serving Flask app "app_mock" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: on
Running on http://127.0.0.1:8050/
Debugger PIN: 706-848-092
Traceback (most recent call last):
  File "/Users/chelsea/venv/venv3/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/chelsea/venv/venv3/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/chelsea/venv/venv3/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/chelsea/venv/venv3/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/chelsea/venv/venv3/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/chelsea/venv/venv3/lib/python3.6/site-packages/flask/app.py", line 1808, in full_dispatch_request
    self.try_trigger_before_first_request_functions()
  File "/Users/chelsea/venv/venv3/lib/python3.6/site-packages/flask/app.py", line 1855, in try_trigger_before_first_request_functions
    func()
  File "/Users/chelsea/venv/venv3/lib/python3.6/site-packages/dash/dash.py", line 995, in _setup_server
    self._validate_layout()
  File "/Users/chelsea/venv/venv3/lib/python3.6/site-packages/dash/dash.py", line 988, in _validate_layout
    ' in the initial layout: `{}`'.format(component_id))
dash.exceptions.DuplicateIdError: Duplicate component id found in the initial layout: `adaptive-switch`
```

it looks like the requirements.txt file is referencing versions with >= so if users have an updated version of dash installed this example will error out even after installing the requirements specified.

cc @shammamah @jackparmer

**Comment by jackparmer** [comment]
Hey @matthewchan15 - do you have time to look at this?

**Comment by matthewchan15** [comment]
@jackparmer hey sorry, have not been using GitHub for a while. If @shammamah isn't looking at it I can take it look.

**Comment by jackparmer** [comment]
https://github.com/plotly/dash-daq-monorepo/pull/5 should do it

**Comment by bpostlethwaite** [comment]
Fixed
